<?php
namespace AWS\AutoScalingPlans;

class AutoScalingPlansClient
{
    /**
     * @param array{ScalingPlanName:string, ApplicationSource:array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}, ScalingInstructions:array<array{ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", MinCapacity:int, MaxCapacity:int, TargetTrackingConfigurations:array<array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}>, PredefinedLoadMetricSpecification?:array{PredefinedLoadMetricType:"ASGTotalCPUUtilization"|"ASGTotalNetworkIn"|"ASGTotalNetworkOut"|"ALBTargetGroupRequestCount", ResourceLabel?:string}, CustomizedLoadMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, ScheduledActionBufferTime?:int, PredictiveScalingMaxCapacityBehavior?:"SetForecastCapacityToMaxCapacity"|"SetMaxCapacityToForecastCapacity"|"SetMaxCapacityAboveForecastCapacity", PredictiveScalingMaxCapacityBuffer?:int, PredictiveScalingMode?:"ForecastAndScale"|"ForecastOnly", ScalingPolicyUpdateBehavior?:"KeepExternalPolicies"|"ReplaceExternalPolicies", DisableDynamicScaling?:bool}>} $args
     * @return \AWS\Result<array{ScalingPlanVersion:int}>
     */
    public function createScalingPlan(array $args): \AWS\Result { }

    /**
     * @param array{ScalingPlanName:string, ApplicationSource:array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}, ScalingInstructions:array<array{ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", MinCapacity:int, MaxCapacity:int, TargetTrackingConfigurations:array<array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}>, PredefinedLoadMetricSpecification?:array{PredefinedLoadMetricType:"ASGTotalCPUUtilization"|"ASGTotalNetworkIn"|"ASGTotalNetworkOut"|"ALBTargetGroupRequestCount", ResourceLabel?:string}, CustomizedLoadMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, ScheduledActionBufferTime?:int, PredictiveScalingMaxCapacityBehavior?:"SetForecastCapacityToMaxCapacity"|"SetMaxCapacityToForecastCapacity"|"SetMaxCapacityAboveForecastCapacity", PredictiveScalingMaxCapacityBuffer?:int, PredictiveScalingMode?:"ForecastAndScale"|"ForecastOnly", ScalingPolicyUpdateBehavior?:"KeepExternalPolicies"|"ReplaceExternalPolicies", DisableDynamicScaling?:bool}>} $args
     * @return \GuzzleHttp\Promise\Promise<array{ScalingPlanVersion:int}>
     */
    public function createScalingPlanAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int} $args
     * @return \AWS\Result<array{}>
     */
    public function deleteScalingPlan(array $args): \AWS\Result { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int} $args
     * @return \GuzzleHttp\Promise\Promise<array{}>
     */
    public function deleteScalingPlanAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int, MaxResults?:int, NextToken?:string} $args
     * @return \AWS\Result<array{ScalingPlanResources?:array<array{ScalingPlanName:string, ScalingPlanVersion:int, ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", ScalingPolicies?:array<array{PolicyName:string, PolicyType:"TargetTrackingScaling", TargetTrackingConfiguration?:array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}}>, ScalingStatusCode:"Inactive"|"PartiallyActive"|"Active", ScalingStatusMessage?:string}>, NextToken?:string}>
     */
    public function describeScalingPlanResources(array $args): \AWS\Result { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int, MaxResults?:int, NextToken?:string} $args
     * @return \GuzzleHttp\Promise\Promise<array{ScalingPlanResources?:array<array{ScalingPlanName:string, ScalingPlanVersion:int, ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", ScalingPolicies?:array<array{PolicyName:string, PolicyType:"TargetTrackingScaling", TargetTrackingConfiguration?:array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}}>, ScalingStatusCode:"Inactive"|"PartiallyActive"|"Active", ScalingStatusMessage?:string}>, NextToken?:string}>
     */
    public function describeScalingPlanResourcesAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ScalingPlanNames?:array<string>, ScalingPlanVersion?:int, ApplicationSources?:array<array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}>, MaxResults?:int, NextToken?:string} $args
     * @return \AWS\Result<array{ScalingPlans?:array<array{ScalingPlanName:string, ScalingPlanVersion:int, ApplicationSource:array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}, ScalingInstructions:array<array{ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", MinCapacity:int, MaxCapacity:int, TargetTrackingConfigurations:array<array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}>, PredefinedLoadMetricSpecification?:array{PredefinedLoadMetricType:"ASGTotalCPUUtilization"|"ASGTotalNetworkIn"|"ASGTotalNetworkOut"|"ALBTargetGroupRequestCount", ResourceLabel?:string}, CustomizedLoadMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, ScheduledActionBufferTime?:int, PredictiveScalingMaxCapacityBehavior?:"SetForecastCapacityToMaxCapacity"|"SetMaxCapacityToForecastCapacity"|"SetMaxCapacityAboveForecastCapacity", PredictiveScalingMaxCapacityBuffer?:int, PredictiveScalingMode?:"ForecastAndScale"|"ForecastOnly", ScalingPolicyUpdateBehavior?:"KeepExternalPolicies"|"ReplaceExternalPolicies", DisableDynamicScaling?:bool}>, StatusCode:"Active"|"ActiveWithProblems"|"CreationInProgress"|"CreationFailed"|"DeletionInProgress"|"DeletionFailed"|"UpdateInProgress"|"UpdateFailed", StatusMessage?:string, StatusStartTime?:int|string|\DateTimeInterface, CreationTime?:int|string|\DateTimeInterface}>, NextToken?:string}>
     */
    public function describeScalingPlans(array $args = []): \AWS\Result { }

    /**
     * @param array{ScalingPlanNames?:array<string>, ScalingPlanVersion?:int, ApplicationSources?:array<array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}>, MaxResults?:int, NextToken?:string} $args
     * @return \GuzzleHttp\Promise\Promise<array{ScalingPlans?:array<array{ScalingPlanName:string, ScalingPlanVersion:int, ApplicationSource:array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}, ScalingInstructions:array<array{ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", MinCapacity:int, MaxCapacity:int, TargetTrackingConfigurations:array<array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}>, PredefinedLoadMetricSpecification?:array{PredefinedLoadMetricType:"ASGTotalCPUUtilization"|"ASGTotalNetworkIn"|"ASGTotalNetworkOut"|"ALBTargetGroupRequestCount", ResourceLabel?:string}, CustomizedLoadMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, ScheduledActionBufferTime?:int, PredictiveScalingMaxCapacityBehavior?:"SetForecastCapacityToMaxCapacity"|"SetMaxCapacityToForecastCapacity"|"SetMaxCapacityAboveForecastCapacity", PredictiveScalingMaxCapacityBuffer?:int, PredictiveScalingMode?:"ForecastAndScale"|"ForecastOnly", ScalingPolicyUpdateBehavior?:"KeepExternalPolicies"|"ReplaceExternalPolicies", DisableDynamicScaling?:bool}>, StatusCode:"Active"|"ActiveWithProblems"|"CreationInProgress"|"CreationFailed"|"DeletionInProgress"|"DeletionFailed"|"UpdateInProgress"|"UpdateFailed", StatusMessage?:string, StatusStartTime?:int|string|\DateTimeInterface, CreationTime?:int|string|\DateTimeInterface}>, NextToken?:string}>
     */
    public function describeScalingPlansAsync(array $args = []): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int, ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", ForecastDataType:"CapacityForecast"|"LoadForecast"|"ScheduledActionMinCapacity"|"ScheduledActionMaxCapacity", StartTime:int|string|\DateTimeInterface, EndTime:int|string|\DateTimeInterface} $args
     * @return \AWS\Result<array{Datapoints:array<array{Timestamp?:int|string|\DateTimeInterface, Value?:float}>}>
     */
    public function getScalingPlanResourceForecastData(array $args): \AWS\Result { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int, ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", ForecastDataType:"CapacityForecast"|"LoadForecast"|"ScheduledActionMinCapacity"|"ScheduledActionMaxCapacity", StartTime:int|string|\DateTimeInterface, EndTime:int|string|\DateTimeInterface} $args
     * @return \GuzzleHttp\Promise\Promise<array{Datapoints:array<array{Timestamp?:int|string|\DateTimeInterface, Value?:float}>}>
     */
    public function getScalingPlanResourceForecastDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int, ApplicationSource?:array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}, ScalingInstructions?:array<array{ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", MinCapacity:int, MaxCapacity:int, TargetTrackingConfigurations:array<array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}>, PredefinedLoadMetricSpecification?:array{PredefinedLoadMetricType:"ASGTotalCPUUtilization"|"ASGTotalNetworkIn"|"ASGTotalNetworkOut"|"ALBTargetGroupRequestCount", ResourceLabel?:string}, CustomizedLoadMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, ScheduledActionBufferTime?:int, PredictiveScalingMaxCapacityBehavior?:"SetForecastCapacityToMaxCapacity"|"SetMaxCapacityToForecastCapacity"|"SetMaxCapacityAboveForecastCapacity", PredictiveScalingMaxCapacityBuffer?:int, PredictiveScalingMode?:"ForecastAndScale"|"ForecastOnly", ScalingPolicyUpdateBehavior?:"KeepExternalPolicies"|"ReplaceExternalPolicies", DisableDynamicScaling?:bool}>} $args
     * @return \AWS\Result<array{}>
     */
    public function updateScalingPlan(array $args): \AWS\Result { }

    /**
     * @param array{ScalingPlanName:string, ScalingPlanVersion:int, ApplicationSource?:array{CloudFormationStackARN?:string, TagFilters?:array<array{Key?:string, Values?:array<string>}>}, ScalingInstructions?:array<array{ServiceNamespace:"autoscaling"|"ecs"|"ec2"|"rds"|"dynamodb", ResourceId:string, ScalableDimension:"autoscaling:autoScalingGroup:DesiredCapacity"|"ecs:service:DesiredCount"|"ec2:spot-fleet-request:TargetCapacity"|"rds:cluster:ReadReplicaCount"|"dynamodb:table:ReadCapacityUnits"|"dynamodb:table:WriteCapacityUnits"|"dynamodb:index:ReadCapacityUnits"|"dynamodb:index:WriteCapacityUnits", MinCapacity:int, MaxCapacity:int, TargetTrackingConfigurations:array<array{PredefinedScalingMetricSpecification?:array{PredefinedScalingMetricType:"ASGAverageCPUUtilization"|"ASGAverageNetworkIn"|"ASGAverageNetworkOut"|"DynamoDBReadCapacityUtilization"|"DynamoDBWriteCapacityUtilization"|"ECSServiceAverageCPUUtilization"|"ECSServiceAverageMemoryUtilization"|"ALBRequestCountPerTarget"|"RDSReaderAverageCPUUtilization"|"RDSReaderAverageDatabaseConnections"|"EC2SpotFleetRequestAverageCPUUtilization"|"EC2SpotFleetRequestAverageNetworkIn"|"EC2SpotFleetRequestAverageNetworkOut", ResourceLabel?:string}, CustomizedScalingMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, TargetValue:float, DisableScaleIn?:bool, ScaleOutCooldown?:int, ScaleInCooldown?:int, EstimatedInstanceWarmup?:int}>, PredefinedLoadMetricSpecification?:array{PredefinedLoadMetricType:"ASGTotalCPUUtilization"|"ASGTotalNetworkIn"|"ASGTotalNetworkOut"|"ALBTargetGroupRequestCount", ResourceLabel?:string}, CustomizedLoadMetricSpecification?:array{MetricName:string, Namespace:string, Dimensions?:array<array{Name:string, Value:string}>, Statistic:"Average"|"Minimum"|"Maximum"|"SampleCount"|"Sum", Unit?:string}, ScheduledActionBufferTime?:int, PredictiveScalingMaxCapacityBehavior?:"SetForecastCapacityToMaxCapacity"|"SetMaxCapacityToForecastCapacity"|"SetMaxCapacityAboveForecastCapacity", PredictiveScalingMaxCapacityBuffer?:int, PredictiveScalingMode?:"ForecastAndScale"|"ForecastOnly", ScalingPolicyUpdateBehavior?:"KeepExternalPolicies"|"ReplaceExternalPolicies", DisableDynamicScaling?:bool}>} $args
     * @return \GuzzleHttp\Promise\Promise<array{}>
     */
    public function updateScalingPlanAsync(array $args): \GuzzleHttp\Promise\Promise { }
}
