<?php
namespace AWS\DLM;

class DLMClient
{
    /**
     * @param array{ExecutionRoleArn:string, Description:string, State:"ENABLED"|"DISABLED", PolicyDetails?:array{PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", ResourceTypes?:array<"VOLUME"|"INSTANCE">, ResourceLocations?:array<"CLOUD"|"OUTPOST"|"LOCAL_ZONE">, TargetTags?:array<array{Key:string, Value:string}>, Schedules?:array<array{Name?:string, CopyTags?:bool, TagsToAdd?:array<array{Key:string, Value:string}>, VariableTags?:array<array{Key:string, Value:string}>, CreateRule?:array{Location?:"CLOUD"|"OUTPOST_LOCAL"|"LOCAL_ZONE", Interval?:int, IntervalUnit?:"HOURS", Times?:array<string>, CronExpression?:string, Scripts?:array<array{Stages?:array<"PRE"|"POST">, ExecutionHandlerService?:"AWS_SYSTEMS_MANAGER", ExecutionHandler:string, ExecuteOperationOnScriptFailure?:bool, ExecutionTimeout?:int, MaximumRetryCount?:int}>}, RetainRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, FastRestoreRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS", AvailabilityZones:array<string>}, CrossRegionCopyRules?:array<array{TargetRegion?:string, Target?:string, Encrypted:bool, CmkArn?:string, CopyTags?:bool, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, DeprecateRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>, ShareRules?:array<array{TargetAccounts:array<string>, UnshareInterval?:int, UnshareIntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}>, DeprecateRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, ArchiveRule?:array{RetainRule:array{RetentionArchiveTier:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}}}>, Parameters?:array{ExcludeBootVolume?:bool, NoReboot?:bool, ExcludeDataVolumeTags?:array<array{Key:string, Value:string}>}, EventSource?:array{Type:"MANAGED_CWE", Parameters?:array{EventType:"shareSnapshot", SnapshotOwner:array<string>, DescriptionRegex:string}}, Actions?:array<array{Name:string, CrossRegionCopy:array<array{Target:string, EncryptionConfiguration:array{Encrypted:bool, CmkArn?:string}, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>}>, PolicyLanguage?:"SIMPLIFIED"|"STANDARD", ResourceType?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, ExtendDeletion?:bool, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}}, Tags?:array<string, string>, DefaultPolicy?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, ExtendDeletion?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}} $args
     * @return \AWS\Result<array{PolicyId?:string}>
     */
    public function createLifecyclePolicy(array $args): \AWS\Result { }

    /**
     * @param array{ExecutionRoleArn:string, Description:string, State:"ENABLED"|"DISABLED", PolicyDetails?:array{PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", ResourceTypes?:array<"VOLUME"|"INSTANCE">, ResourceLocations?:array<"CLOUD"|"OUTPOST"|"LOCAL_ZONE">, TargetTags?:array<array{Key:string, Value:string}>, Schedules?:array<array{Name?:string, CopyTags?:bool, TagsToAdd?:array<array{Key:string, Value:string}>, VariableTags?:array<array{Key:string, Value:string}>, CreateRule?:array{Location?:"CLOUD"|"OUTPOST_LOCAL"|"LOCAL_ZONE", Interval?:int, IntervalUnit?:"HOURS", Times?:array<string>, CronExpression?:string, Scripts?:array<array{Stages?:array<"PRE"|"POST">, ExecutionHandlerService?:"AWS_SYSTEMS_MANAGER", ExecutionHandler:string, ExecuteOperationOnScriptFailure?:bool, ExecutionTimeout?:int, MaximumRetryCount?:int}>}, RetainRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, FastRestoreRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS", AvailabilityZones:array<string>}, CrossRegionCopyRules?:array<array{TargetRegion?:string, Target?:string, Encrypted:bool, CmkArn?:string, CopyTags?:bool, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, DeprecateRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>, ShareRules?:array<array{TargetAccounts:array<string>, UnshareInterval?:int, UnshareIntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}>, DeprecateRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, ArchiveRule?:array{RetainRule:array{RetentionArchiveTier:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}}}>, Parameters?:array{ExcludeBootVolume?:bool, NoReboot?:bool, ExcludeDataVolumeTags?:array<array{Key:string, Value:string}>}, EventSource?:array{Type:"MANAGED_CWE", Parameters?:array{EventType:"shareSnapshot", SnapshotOwner:array<string>, DescriptionRegex:string}}, Actions?:array<array{Name:string, CrossRegionCopy:array<array{Target:string, EncryptionConfiguration:array{Encrypted:bool, CmkArn?:string}, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>}>, PolicyLanguage?:"SIMPLIFIED"|"STANDARD", ResourceType?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, ExtendDeletion?:bool, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}}, Tags?:array<string, string>, DefaultPolicy?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, ExtendDeletion?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}} $args
     * @return \GuzzleHttp\Promise\Promise<array{PolicyId?:string}>
     */
    public function createLifecyclePolicyAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{PolicyId:string} $args
     * @return \AWS\Result<array{}>
     */
    public function deleteLifecyclePolicy(array $args): \AWS\Result { }

    /**
     * @param array{PolicyId:string} $args
     * @return \GuzzleHttp\Promise\Promise<array{}>
     */
    public function deleteLifecyclePolicyAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{PolicyIds?:array<string>, State?:"ENABLED"|"DISABLED"|"ERROR", ResourceTypes?:array<"VOLUME"|"INSTANCE">, TargetTags?:array<string>, TagsToAdd?:array<string>, DefaultPolicyType?:"VOLUME"|"INSTANCE"|"ALL"} $args
     * @return \AWS\Result<array{Policies?:array<array{PolicyId?:string, Description?:string, State?:"ENABLED"|"DISABLED"|"ERROR", Tags?:array<string, string>, PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", DefaultPolicy?:bool}>}>
     */
    public function getLifecyclePolicies(array $args = []): \AWS\Result { }

    /**
     * @param array{PolicyIds?:array<string>, State?:"ENABLED"|"DISABLED"|"ERROR", ResourceTypes?:array<"VOLUME"|"INSTANCE">, TargetTags?:array<string>, TagsToAdd?:array<string>, DefaultPolicyType?:"VOLUME"|"INSTANCE"|"ALL"} $args
     * @return \GuzzleHttp\Promise\Promise<array{Policies?:array<array{PolicyId?:string, Description?:string, State?:"ENABLED"|"DISABLED"|"ERROR", Tags?:array<string, string>, PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", DefaultPolicy?:bool}>}>
     */
    public function getLifecyclePoliciesAsync(array $args = []): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{PolicyId:string} $args
     * @return \AWS\Result<array{Policy?:array{PolicyId?:string, Description?:string, State?:"ENABLED"|"DISABLED"|"ERROR", StatusMessage?:string, ExecutionRoleArn?:string, DateCreated?:int|string|\DateTimeInterface, DateModified?:int|string|\DateTimeInterface, PolicyDetails?:array{PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", ResourceTypes?:array<"VOLUME"|"INSTANCE">, ResourceLocations?:array<"CLOUD"|"OUTPOST"|"LOCAL_ZONE">, TargetTags?:array<array{Key:string, Value:string}>, Schedules?:array<array{Name?:string, CopyTags?:bool, TagsToAdd?:array<array{Key:string, Value:string}>, VariableTags?:array<array{Key:string, Value:string}>, CreateRule?:array{Location?:"CLOUD"|"OUTPOST_LOCAL"|"LOCAL_ZONE", Interval?:int, IntervalUnit?:"HOURS", Times?:array<string>, CronExpression?:string, Scripts?:array<array{Stages?:array<"PRE"|"POST">, ExecutionHandlerService?:"AWS_SYSTEMS_MANAGER", ExecutionHandler:string, ExecuteOperationOnScriptFailure?:bool, ExecutionTimeout?:int, MaximumRetryCount?:int}>}, RetainRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, FastRestoreRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS", AvailabilityZones:array<string>}, CrossRegionCopyRules?:array<array{TargetRegion?:string, Target?:string, Encrypted:bool, CmkArn?:string, CopyTags?:bool, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, DeprecateRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>, ShareRules?:array<array{TargetAccounts:array<string>, UnshareInterval?:int, UnshareIntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}>, DeprecateRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, ArchiveRule?:array{RetainRule:array{RetentionArchiveTier:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}}}>, Parameters?:array{ExcludeBootVolume?:bool, NoReboot?:bool, ExcludeDataVolumeTags?:array<array{Key:string, Value:string}>}, EventSource?:array{Type:"MANAGED_CWE", Parameters?:array{EventType:"shareSnapshot", SnapshotOwner:array<string>, DescriptionRegex:string}}, Actions?:array<array{Name:string, CrossRegionCopy:array<array{Target:string, EncryptionConfiguration:array{Encrypted:bool, CmkArn?:string}, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>}>, PolicyLanguage?:"SIMPLIFIED"|"STANDARD", ResourceType?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, ExtendDeletion?:bool, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}}, Tags?:array<string, string>, PolicyArn?:string, DefaultPolicy?:bool}}>
     */
    public function getLifecyclePolicy(array $args): \AWS\Result { }

    /**
     * @param array{PolicyId:string} $args
     * @return \GuzzleHttp\Promise\Promise<array{Policy?:array{PolicyId?:string, Description?:string, State?:"ENABLED"|"DISABLED"|"ERROR", StatusMessage?:string, ExecutionRoleArn?:string, DateCreated?:int|string|\DateTimeInterface, DateModified?:int|string|\DateTimeInterface, PolicyDetails?:array{PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", ResourceTypes?:array<"VOLUME"|"INSTANCE">, ResourceLocations?:array<"CLOUD"|"OUTPOST"|"LOCAL_ZONE">, TargetTags?:array<array{Key:string, Value:string}>, Schedules?:array<array{Name?:string, CopyTags?:bool, TagsToAdd?:array<array{Key:string, Value:string}>, VariableTags?:array<array{Key:string, Value:string}>, CreateRule?:array{Location?:"CLOUD"|"OUTPOST_LOCAL"|"LOCAL_ZONE", Interval?:int, IntervalUnit?:"HOURS", Times?:array<string>, CronExpression?:string, Scripts?:array<array{Stages?:array<"PRE"|"POST">, ExecutionHandlerService?:"AWS_SYSTEMS_MANAGER", ExecutionHandler:string, ExecuteOperationOnScriptFailure?:bool, ExecutionTimeout?:int, MaximumRetryCount?:int}>}, RetainRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, FastRestoreRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS", AvailabilityZones:array<string>}, CrossRegionCopyRules?:array<array{TargetRegion?:string, Target?:string, Encrypted:bool, CmkArn?:string, CopyTags?:bool, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, DeprecateRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>, ShareRules?:array<array{TargetAccounts:array<string>, UnshareInterval?:int, UnshareIntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}>, DeprecateRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, ArchiveRule?:array{RetainRule:array{RetentionArchiveTier:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}}}>, Parameters?:array{ExcludeBootVolume?:bool, NoReboot?:bool, ExcludeDataVolumeTags?:array<array{Key:string, Value:string}>}, EventSource?:array{Type:"MANAGED_CWE", Parameters?:array{EventType:"shareSnapshot", SnapshotOwner:array<string>, DescriptionRegex:string}}, Actions?:array<array{Name:string, CrossRegionCopy:array<array{Target:string, EncryptionConfiguration:array{Encrypted:bool, CmkArn?:string}, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>}>, PolicyLanguage?:"SIMPLIFIED"|"STANDARD", ResourceType?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, ExtendDeletion?:bool, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}}, Tags?:array<string, string>, PolicyArn?:string, DefaultPolicy?:bool}}>
     */
    public function getLifecyclePolicyAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ResourceArn:string} $args
     * @return \AWS\Result<array{Tags?:array<string, string>}>
     */
    public function listTagsForResource(array $args): \AWS\Result { }

    /**
     * @param array{ResourceArn:string} $args
     * @return \GuzzleHttp\Promise\Promise<array{Tags?:array<string, string>}>
     */
    public function listTagsForResourceAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ResourceArn:string, Tags:array<string, string>} $args
     * @return \AWS\Result<array{}>
     */
    public function tagResource(array $args): \AWS\Result { }

    /**
     * @param array{ResourceArn:string, Tags:array<string, string>} $args
     * @return \GuzzleHttp\Promise\Promise<array{}>
     */
    public function tagResourceAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{ResourceArn:string, TagKeys:array<string>} $args
     * @return \AWS\Result<array{}>
     */
    public function untagResource(array $args): \AWS\Result { }

    /**
     * @param array{ResourceArn:string, TagKeys:array<string>} $args
     * @return \GuzzleHttp\Promise\Promise<array{}>
     */
    public function untagResourceAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{PolicyId:string, ExecutionRoleArn?:string, State?:"ENABLED"|"DISABLED", Description?:string, PolicyDetails?:array{PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", ResourceTypes?:array<"VOLUME"|"INSTANCE">, ResourceLocations?:array<"CLOUD"|"OUTPOST"|"LOCAL_ZONE">, TargetTags?:array<array{Key:string, Value:string}>, Schedules?:array<array{Name?:string, CopyTags?:bool, TagsToAdd?:array<array{Key:string, Value:string}>, VariableTags?:array<array{Key:string, Value:string}>, CreateRule?:array{Location?:"CLOUD"|"OUTPOST_LOCAL"|"LOCAL_ZONE", Interval?:int, IntervalUnit?:"HOURS", Times?:array<string>, CronExpression?:string, Scripts?:array<array{Stages?:array<"PRE"|"POST">, ExecutionHandlerService?:"AWS_SYSTEMS_MANAGER", ExecutionHandler:string, ExecuteOperationOnScriptFailure?:bool, ExecutionTimeout?:int, MaximumRetryCount?:int}>}, RetainRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, FastRestoreRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS", AvailabilityZones:array<string>}, CrossRegionCopyRules?:array<array{TargetRegion?:string, Target?:string, Encrypted:bool, CmkArn?:string, CopyTags?:bool, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, DeprecateRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>, ShareRules?:array<array{TargetAccounts:array<string>, UnshareInterval?:int, UnshareIntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}>, DeprecateRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, ArchiveRule?:array{RetainRule:array{RetentionArchiveTier:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}}}>, Parameters?:array{ExcludeBootVolume?:bool, NoReboot?:bool, ExcludeDataVolumeTags?:array<array{Key:string, Value:string}>}, EventSource?:array{Type:"MANAGED_CWE", Parameters?:array{EventType:"shareSnapshot", SnapshotOwner:array<string>, DescriptionRegex:string}}, Actions?:array<array{Name:string, CrossRegionCopy:array<array{Target:string, EncryptionConfiguration:array{Encrypted:bool, CmkArn?:string}, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>}>, PolicyLanguage?:"SIMPLIFIED"|"STANDARD", ResourceType?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, ExtendDeletion?:bool, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}}, CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, ExtendDeletion?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}} $args
     * @return \AWS\Result<array{}>
     */
    public function updateLifecyclePolicy(array $args): \AWS\Result { }

    /**
     * @param array{PolicyId:string, ExecutionRoleArn?:string, State?:"ENABLED"|"DISABLED", Description?:string, PolicyDetails?:array{PolicyType?:"EBS_SNAPSHOT_MANAGEMENT"|"IMAGE_MANAGEMENT"|"EVENT_BASED_POLICY", ResourceTypes?:array<"VOLUME"|"INSTANCE">, ResourceLocations?:array<"CLOUD"|"OUTPOST"|"LOCAL_ZONE">, TargetTags?:array<array{Key:string, Value:string}>, Schedules?:array<array{Name?:string, CopyTags?:bool, TagsToAdd?:array<array{Key:string, Value:string}>, VariableTags?:array<array{Key:string, Value:string}>, CreateRule?:array{Location?:"CLOUD"|"OUTPOST_LOCAL"|"LOCAL_ZONE", Interval?:int, IntervalUnit?:"HOURS", Times?:array<string>, CronExpression?:string, Scripts?:array<array{Stages?:array<"PRE"|"POST">, ExecutionHandlerService?:"AWS_SYSTEMS_MANAGER", ExecutionHandler:string, ExecuteOperationOnScriptFailure?:bool, ExecutionTimeout?:int, MaximumRetryCount?:int}>}, RetainRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, FastRestoreRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS", AvailabilityZones:array<string>}, CrossRegionCopyRules?:array<array{TargetRegion?:string, Target?:string, Encrypted:bool, CmkArn?:string, CopyTags?:bool, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, DeprecateRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>, ShareRules?:array<array{TargetAccounts:array<string>, UnshareInterval?:int, UnshareIntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}>, DeprecateRule?:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}, ArchiveRule?:array{RetainRule:array{RetentionArchiveTier:array{Count?:int, Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}}}>, Parameters?:array{ExcludeBootVolume?:bool, NoReboot?:bool, ExcludeDataVolumeTags?:array<array{Key:string, Value:string}>}, EventSource?:array{Type:"MANAGED_CWE", Parameters?:array{EventType:"shareSnapshot", SnapshotOwner:array<string>, DescriptionRegex:string}}, Actions?:array<array{Name:string, CrossRegionCopy:array<array{Target:string, EncryptionConfiguration:array{Encrypted:bool, CmkArn?:string}, RetainRule?:array{Interval?:int, IntervalUnit?:"DAYS"|"WEEKS"|"MONTHS"|"YEARS"}}>}>, PolicyLanguage?:"SIMPLIFIED"|"STANDARD", ResourceType?:"VOLUME"|"INSTANCE", CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, ExtendDeletion?:bool, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}}, CreateInterval?:int, RetainInterval?:int, CopyTags?:bool, ExtendDeletion?:bool, CrossRegionCopyTargets?:array<array{TargetRegion?:string}>, Exclusions?:array{ExcludeBootVolumes?:bool, ExcludeVolumeTypes?:array<string>, ExcludeTags?:array<array{Key:string, Value:string}>}} $args
     * @return \GuzzleHttp\Promise\Promise<array{}>
     */
    public function updateLifecyclePolicyAsync(array $args): \GuzzleHttp\Promise\Promise { }
}
