<?php
namespace AWS\PaymentCryptographyData;

class PaymentCryptographyDataClient
{
    /**
     * @param array{KeyIdentifier:string, CipherText:string, DecryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Asymmetric?:array{PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}, Emv?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionDerivationData:string, Mode?:"ECB"|"CBC", InitializationVector?:string}}, WrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string, PlainText:string}>
     */
    public function decryptData(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, CipherText:string, DecryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Asymmetric?:array{PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}, Emv?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionDerivationData:string, Mode?:"ECB"|"CBC", InitializationVector?:string}}, WrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string, PlainText:string}>
     */
    public function decryptDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{KeyIdentifier:string, PlainText:string, EncryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Asymmetric?:array{PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}, Emv?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionDerivationData:string, Mode?:"ECB"|"CBC", InitializationVector?:string}}, WrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue?:string, CipherText:string}>
     */
    public function encryptData(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, PlainText:string, EncryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Asymmetric?:array{PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}, Emv?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionDerivationData:string, Mode?:"ECB"|"CBC", InitializationVector?:string}}, WrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue?:string, CipherText:string}>
     */
    public function encryptDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{KeyIdentifier:string, PrimaryAccountNumber:string, GenerationAttributes:array{AmexCardSecurityCodeVersion1?:array{CardExpiryDate:string}, AmexCardSecurityCodeVersion2?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue1?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue2?:array{CardExpiryDate:string}, CardHolderVerificationValue?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, DynamicCardVerificationCode?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, TrackData:string}, DynamicCardVerificationValue?:array{PanSequenceNumber:string, CardExpiryDate:string, ServiceCode:string, ApplicationTransactionCounter:string}}, ValidationDataLength?:int} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string, ValidationData:string}>
     */
    public function generateCardValidationData(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, PrimaryAccountNumber:string, GenerationAttributes:array{AmexCardSecurityCodeVersion1?:array{CardExpiryDate:string}, AmexCardSecurityCodeVersion2?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue1?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue2?:array{CardExpiryDate:string}, CardHolderVerificationValue?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, DynamicCardVerificationCode?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, TrackData:string}, DynamicCardVerificationValue?:array{PanSequenceNumber:string, CardExpiryDate:string, ServiceCode:string, ApplicationTransactionCounter:string}}, ValidationDataLength?:int} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string, ValidationData:string}>
     */
    public function generateCardValidationDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{KeyIdentifier:string, MessageData:string, GenerationAttributes:array{Algorithm?:"ISO9797_ALGORITHM1"|"ISO9797_ALGORITHM3"|"CMAC"|"HMAC_SHA224"|"HMAC_SHA256"|"HMAC_SHA384"|"HMAC_SHA512", EmvMac?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionKeyDerivationMode:"EMV_COMMON_SESSION_KEY"|"EMV2000"|"AMEX"|"MASTERCARD_SESSION_KEY"|"VISA", SessionKeyDerivationValue:array{ApplicationCryptogram?:string, ApplicationTransactionCounter?:string}}, DukptIso9797Algorithm1?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptIso9797Algorithm3?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptCmac?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}}, MacLength?:int} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string, Mac:string}>
     */
    public function generateMac(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, MessageData:string, GenerationAttributes:array{Algorithm?:"ISO9797_ALGORITHM1"|"ISO9797_ALGORITHM3"|"CMAC"|"HMAC_SHA224"|"HMAC_SHA256"|"HMAC_SHA384"|"HMAC_SHA512", EmvMac?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionKeyDerivationMode:"EMV_COMMON_SESSION_KEY"|"EMV2000"|"AMEX"|"MASTERCARD_SESSION_KEY"|"VISA", SessionKeyDerivationValue:array{ApplicationCryptogram?:string, ApplicationTransactionCounter?:string}}, DukptIso9797Algorithm1?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptIso9797Algorithm3?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptCmac?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}}, MacLength?:int} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string, Mac:string}>
     */
    public function generateMacAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{NewPinPekIdentifier:string, NewEncryptedPinBlock:string, PinBlockFormat:"ISO_FORMAT_0"|"ISO_FORMAT_1"|"ISO_FORMAT_3", SecureMessagingIntegrityKeyIdentifier:string, SecureMessagingConfidentialityKeyIdentifier:string, MessageData:string, DerivationMethodAttributes:array{EmvCommon?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationCryptogram:string, Mode:"ECB"|"CBC", PinBlockPaddingType:"NO_PADDING"|"ISO_IEC_7816_4", PinBlockLengthPosition:"NONE"|"FRONT_OF_PIN_BLOCK"}, Amex?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, AuthorizationRequestKeyIdentifier:string, CurrentPinAttributes?:array{CurrentPinPekIdentifier:string, CurrentEncryptedPinBlock:string}}, Visa?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, AuthorizationRequestKeyIdentifier:string, CurrentPinAttributes?:array{CurrentPinPekIdentifier:string, CurrentEncryptedPinBlock:string}}, Emv2000?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, Mastercard?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationCryptogram:string}}} $args
     * @return \AWS\Result<array{NewPinPekArn:string, SecureMessagingIntegrityKeyArn:string, SecureMessagingConfidentialityKeyArn:string, Mac:string, EncryptedPinBlock:string, NewPinPekKeyCheckValue:string, SecureMessagingIntegrityKeyCheckValue:string, SecureMessagingConfidentialityKeyCheckValue:string, VisaAmexDerivationOutputs?:array{AuthorizationRequestKeyArn:string, AuthorizationRequestKeyCheckValue:string, CurrentPinPekArn?:string, CurrentPinPekKeyCheckValue?:string}}>
     */
    public function generateMacEmvPinChange(array $args): \AWS\Result { }

    /**
     * @param array{NewPinPekIdentifier:string, NewEncryptedPinBlock:string, PinBlockFormat:"ISO_FORMAT_0"|"ISO_FORMAT_1"|"ISO_FORMAT_3", SecureMessagingIntegrityKeyIdentifier:string, SecureMessagingConfidentialityKeyIdentifier:string, MessageData:string, DerivationMethodAttributes:array{EmvCommon?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationCryptogram:string, Mode:"ECB"|"CBC", PinBlockPaddingType:"NO_PADDING"|"ISO_IEC_7816_4", PinBlockLengthPosition:"NONE"|"FRONT_OF_PIN_BLOCK"}, Amex?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, AuthorizationRequestKeyIdentifier:string, CurrentPinAttributes?:array{CurrentPinPekIdentifier:string, CurrentEncryptedPinBlock:string}}, Visa?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, AuthorizationRequestKeyIdentifier:string, CurrentPinAttributes?:array{CurrentPinPekIdentifier:string, CurrentEncryptedPinBlock:string}}, Emv2000?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, Mastercard?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationCryptogram:string}}} $args
     * @return \GuzzleHttp\Promise\Promise<array{NewPinPekArn:string, SecureMessagingIntegrityKeyArn:string, SecureMessagingConfidentialityKeyArn:string, Mac:string, EncryptedPinBlock:string, NewPinPekKeyCheckValue:string, SecureMessagingIntegrityKeyCheckValue:string, SecureMessagingConfidentialityKeyCheckValue:string, VisaAmexDerivationOutputs?:array{AuthorizationRequestKeyArn:string, AuthorizationRequestKeyCheckValue:string, CurrentPinPekArn?:string, CurrentPinPekKeyCheckValue?:string}}>
     */
    public function generateMacEmvPinChangeAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{GenerationKeyIdentifier:string, EncryptionKeyIdentifier:string, GenerationAttributes:array{VisaPin?:array{PinVerificationKeyIndex:int}, VisaPinVerificationValue?:array{EncryptedPinBlock:string, PinVerificationKeyIndex:int}, Ibm3624PinOffset?:array{EncryptedPinBlock:string, DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string}, Ibm3624NaturalPin?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string}, Ibm3624RandomPin?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string}, Ibm3624PinFromOffset?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string, PinOffset:string}}, PinDataLength?:int, PrimaryAccountNumber:string, PinBlockFormat:"ISO_FORMAT_0"|"ISO_FORMAT_3"|"ISO_FORMAT_4", EncryptionWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \AWS\Result<array{GenerationKeyArn:string, GenerationKeyCheckValue:string, EncryptionKeyArn:string, EncryptionKeyCheckValue:string, EncryptedPinBlock:string, PinData:array{PinOffset?:string, VerificationValue?:string}}>
     */
    public function generatePinData(array $args): \AWS\Result { }

    /**
     * @param array{GenerationKeyIdentifier:string, EncryptionKeyIdentifier:string, GenerationAttributes:array{VisaPin?:array{PinVerificationKeyIndex:int}, VisaPinVerificationValue?:array{EncryptedPinBlock:string, PinVerificationKeyIndex:int}, Ibm3624PinOffset?:array{EncryptedPinBlock:string, DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string}, Ibm3624NaturalPin?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string}, Ibm3624RandomPin?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string}, Ibm3624PinFromOffset?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string, PinOffset:string}}, PinDataLength?:int, PrimaryAccountNumber:string, PinBlockFormat:"ISO_FORMAT_0"|"ISO_FORMAT_3"|"ISO_FORMAT_4", EncryptionWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \GuzzleHttp\Promise\Promise<array{GenerationKeyArn:string, GenerationKeyCheckValue:string, EncryptionKeyArn:string, EncryptionKeyCheckValue:string, EncryptedPinBlock:string, PinData:array{PinOffset?:string, VerificationValue?:string}}>
     */
    public function generatePinDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{IncomingKeyIdentifier:string, OutgoingKeyIdentifier:string, CipherText:string, IncomingEncryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}}, OutgoingEncryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}}, IncomingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}, OutgoingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string, CipherText:string}>
     */
    public function reEncryptData(array $args): \AWS\Result { }

    /**
     * @param array{IncomingKeyIdentifier:string, OutgoingKeyIdentifier:string, CipherText:string, IncomingEncryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}}, OutgoingEncryptionAttributes:array{Symmetric?:array{Mode:"ECB"|"CBC"|"CFB"|"CFB1"|"CFB8"|"CFB64"|"CFB128"|"OFB", InitializationVector?:string, PaddingType?:"PKCS1"|"OAEP_SHA1"|"OAEP_SHA256"|"OAEP_SHA512"}, Dukpt?:array{KeySerialNumber:string, Mode?:"ECB"|"CBC", DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", InitializationVector?:string}}, IncomingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}, OutgoingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string, CipherText:string}>
     */
    public function reEncryptDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{IncomingKeyIdentifier:string, OutgoingKeyIdentifier:string, IncomingTranslationAttributes:array{IsoFormat0?:array{PrimaryAccountNumber:string}, IsoFormat1?:array{}, IsoFormat3?:array{PrimaryAccountNumber:string}, IsoFormat4?:array{PrimaryAccountNumber:string}}, OutgoingTranslationAttributes:array{IsoFormat0?:array{PrimaryAccountNumber:string}, IsoFormat1?:array{}, IsoFormat3?:array{PrimaryAccountNumber:string}, IsoFormat4?:array{PrimaryAccountNumber:string}}, EncryptedPinBlock:string, IncomingDukptAttributes?:array{KeySerialNumber:string, DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE"}, OutgoingDukptAttributes?:array{KeySerialNumber:string, DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE"}, IncomingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}, OutgoingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \AWS\Result<array{PinBlock:string, KeyArn:string, KeyCheckValue:string}>
     */
    public function translatePinData(array $args): \AWS\Result { }

    /**
     * @param array{IncomingKeyIdentifier:string, OutgoingKeyIdentifier:string, IncomingTranslationAttributes:array{IsoFormat0?:array{PrimaryAccountNumber:string}, IsoFormat1?:array{}, IsoFormat3?:array{PrimaryAccountNumber:string}, IsoFormat4?:array{PrimaryAccountNumber:string}}, OutgoingTranslationAttributes:array{IsoFormat0?:array{PrimaryAccountNumber:string}, IsoFormat1?:array{}, IsoFormat3?:array{PrimaryAccountNumber:string}, IsoFormat4?:array{PrimaryAccountNumber:string}}, EncryptedPinBlock:string, IncomingDukptAttributes?:array{KeySerialNumber:string, DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE"}, OutgoingDukptAttributes?:array{KeySerialNumber:string, DukptKeyDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", DukptKeyVariant?:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE"}, IncomingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}, OutgoingWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \GuzzleHttp\Promise\Promise<array{PinBlock:string, KeyArn:string, KeyCheckValue:string}>
     */
    public function translatePinDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{KeyIdentifier:string, TransactionData:string, AuthRequestCryptogram:string, MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", SessionKeyDerivationAttributes:array{EmvCommon?:array{PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, Mastercard?:array{PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, UnpredictableNumber:string}, Emv2000?:array{PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, Amex?:array{PrimaryAccountNumber:string, PanSequenceNumber:string}, Visa?:array{PrimaryAccountNumber:string, PanSequenceNumber:string}}, AuthResponseAttributes?:array{ArpcMethod1?:array{AuthResponseCode:string}, ArpcMethod2?:array{CardStatusUpdate:string, ProprietaryAuthenticationData?:string}}} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string, AuthResponseValue?:string}>
     */
    public function verifyAuthRequestCryptogram(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, TransactionData:string, AuthRequestCryptogram:string, MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", SessionKeyDerivationAttributes:array{EmvCommon?:array{PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, Mastercard?:array{PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, UnpredictableNumber:string}, Emv2000?:array{PrimaryAccountNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, Amex?:array{PrimaryAccountNumber:string, PanSequenceNumber:string}, Visa?:array{PrimaryAccountNumber:string, PanSequenceNumber:string}}, AuthResponseAttributes?:array{ArpcMethod1?:array{AuthResponseCode:string}, ArpcMethod2?:array{CardStatusUpdate:string, ProprietaryAuthenticationData?:string}}} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string, AuthResponseValue?:string}>
     */
    public function verifyAuthRequestCryptogramAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{KeyIdentifier:string, PrimaryAccountNumber:string, VerificationAttributes:array{AmexCardSecurityCodeVersion1?:array{CardExpiryDate:string}, AmexCardSecurityCodeVersion2?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue1?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue2?:array{CardExpiryDate:string}, CardHolderVerificationValue?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, DynamicCardVerificationCode?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, TrackData:string}, DynamicCardVerificationValue?:array{PanSequenceNumber:string, CardExpiryDate:string, ServiceCode:string, ApplicationTransactionCounter:string}, DiscoverDynamicCardVerificationCode?:array{CardExpiryDate:string, UnpredictableNumber:string, ApplicationTransactionCounter:string}}, ValidationData:string} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string}>
     */
    public function verifyCardValidationData(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, PrimaryAccountNumber:string, VerificationAttributes:array{AmexCardSecurityCodeVersion1?:array{CardExpiryDate:string}, AmexCardSecurityCodeVersion2?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue1?:array{CardExpiryDate:string, ServiceCode:string}, CardVerificationValue2?:array{CardExpiryDate:string}, CardHolderVerificationValue?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string}, DynamicCardVerificationCode?:array{UnpredictableNumber:string, PanSequenceNumber:string, ApplicationTransactionCounter:string, TrackData:string}, DynamicCardVerificationValue?:array{PanSequenceNumber:string, CardExpiryDate:string, ServiceCode:string, ApplicationTransactionCounter:string}, DiscoverDynamicCardVerificationCode?:array{CardExpiryDate:string, UnpredictableNumber:string, ApplicationTransactionCounter:string}}, ValidationData:string} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string}>
     */
    public function verifyCardValidationDataAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{KeyIdentifier:string, MessageData:string, Mac:string, VerificationAttributes:array{Algorithm?:"ISO9797_ALGORITHM1"|"ISO9797_ALGORITHM3"|"CMAC"|"HMAC_SHA224"|"HMAC_SHA256"|"HMAC_SHA384"|"HMAC_SHA512", EmvMac?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionKeyDerivationMode:"EMV_COMMON_SESSION_KEY"|"EMV2000"|"AMEX"|"MASTERCARD_SESSION_KEY"|"VISA", SessionKeyDerivationValue:array{ApplicationCryptogram?:string, ApplicationTransactionCounter?:string}}, DukptIso9797Algorithm1?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptIso9797Algorithm3?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptCmac?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}}, MacLength?:int} $args
     * @return \AWS\Result<array{KeyArn:string, KeyCheckValue:string}>
     */
    public function verifyMac(array $args): \AWS\Result { }

    /**
     * @param array{KeyIdentifier:string, MessageData:string, Mac:string, VerificationAttributes:array{Algorithm?:"ISO9797_ALGORITHM1"|"ISO9797_ALGORITHM3"|"CMAC"|"HMAC_SHA224"|"HMAC_SHA256"|"HMAC_SHA384"|"HMAC_SHA512", EmvMac?:array{MajorKeyDerivationMode:"EMV_OPTION_A"|"EMV_OPTION_B", PrimaryAccountNumber:string, PanSequenceNumber:string, SessionKeyDerivationMode:"EMV_COMMON_SESSION_KEY"|"EMV2000"|"AMEX"|"MASTERCARD_SESSION_KEY"|"VISA", SessionKeyDerivationValue:array{ApplicationCryptogram?:string, ApplicationTransactionCounter?:string}}, DukptIso9797Algorithm1?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptIso9797Algorithm3?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, DukptCmac?:array{KeySerialNumber:string, DukptKeyVariant:"BIDIRECTIONAL"|"REQUEST"|"RESPONSE", DukptDerivationType?:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}}, MacLength?:int} $args
     * @return \GuzzleHttp\Promise\Promise<array{KeyArn:string, KeyCheckValue:string}>
     */
    public function verifyMacAsync(array $args): \GuzzleHttp\Promise\Promise { }

    /**
     * @param array{VerificationKeyIdentifier:string, EncryptionKeyIdentifier:string, VerificationAttributes:array{VisaPin?:array{PinVerificationKeyIndex:int, VerificationValue:string}, Ibm3624Pin?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string, PinOffset:string}}, EncryptedPinBlock:string, PrimaryAccountNumber:string, PinBlockFormat:"ISO_FORMAT_0"|"ISO_FORMAT_3"|"ISO_FORMAT_4", PinDataLength?:int, DukptAttributes?:array{KeySerialNumber:string, DukptDerivationType:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, EncryptionWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \AWS\Result<array{VerificationKeyArn:string, VerificationKeyCheckValue:string, EncryptionKeyArn:string, EncryptionKeyCheckValue:string}>
     */
    public function verifyPinData(array $args): \AWS\Result { }

    /**
     * @param array{VerificationKeyIdentifier:string, EncryptionKeyIdentifier:string, VerificationAttributes:array{VisaPin?:array{PinVerificationKeyIndex:int, VerificationValue:string}, Ibm3624Pin?:array{DecimalizationTable:string, PinValidationDataPadCharacter:string, PinValidationData:string, PinOffset:string}}, EncryptedPinBlock:string, PrimaryAccountNumber:string, PinBlockFormat:"ISO_FORMAT_0"|"ISO_FORMAT_3"|"ISO_FORMAT_4", PinDataLength?:int, DukptAttributes?:array{KeySerialNumber:string, DukptDerivationType:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256"}, EncryptionWrappedKey?:array{WrappedKeyMaterial:array{Tr31KeyBlock?:string, DiffieHellmanSymmetricKey?:array{CertificateAuthorityPublicKeyIdentifier:string, PublicKeyCertificate:string, KeyAlgorithm:"TDES_2KEY"|"TDES_3KEY"|"AES_128"|"AES_192"|"AES_256", KeyDerivationFunction:"NIST_SP800"|"ANSI_X963", KeyDerivationHashAlgorithm:"SHA_256"|"SHA_384"|"SHA_512", SharedInformation:string}}, KeyCheckValueAlgorithm?:"CMAC"|"ANSI_X9_24"}} $args
     * @return \GuzzleHttp\Promise\Promise<array{VerificationKeyArn:string, VerificationKeyCheckValue:string, EncryptionKeyArn:string, EncryptionKeyCheckValue:string}>
     */
    public function verifyPinDataAsync(array $args): \GuzzleHttp\Promise\Promise { }
}
