<?php
namespace AWS\QLDBSession;

class QLDBSessionClient
{
    /**
     * @param array{SessionToken?:string, StartSession?:array{LedgerName:string}, StartTransaction?:array{}, EndSession?:array{}, CommitTransaction?:array{TransactionId:string, CommitDigest:string|resource|\Psr\Http\Message\StreamInterface}, AbortTransaction?:array{}, ExecuteStatement?:array{TransactionId:string, Statement:string, Parameters?:array<array{IonBinary?:string|resource|\Psr\Http\Message\StreamInterface, IonText?:string}>}, FetchPage?:array{TransactionId:string, NextPageToken:string}} $args
     * @return \AWS\Result<array{StartSession?:array{SessionToken?:string, TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, StartTransaction?:array{TransactionId?:string, TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, EndSession?:array{TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, CommitTransaction?:array{TransactionId?:string, CommitDigest?:string|resource|\Psr\Http\Message\StreamInterface, TimingInformation?:array{ProcessingTimeMilliseconds?:int}, ConsumedIOs?:array{ReadIOs?:int, WriteIOs?:int}}, AbortTransaction?:array{TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, ExecuteStatement?:array{FirstPage?:array{Values?:array<array{IonBinary?:string|resource|\Psr\Http\Message\StreamInterface, IonText?:string}>, NextPageToken?:string}, TimingInformation?:array{ProcessingTimeMilliseconds?:int}, ConsumedIOs?:array{ReadIOs?:int, WriteIOs?:int}}, FetchPage?:array{Page?:array{Values?:array<array{IonBinary?:string|resource|\Psr\Http\Message\StreamInterface, IonText?:string}>, NextPageToken?:string}, TimingInformation?:array{ProcessingTimeMilliseconds?:int}, ConsumedIOs?:array{ReadIOs?:int, WriteIOs?:int}}}>
     */
    public function sendCommand(array $args = []): \AWS\Result { }

    /**
     * @param array{SessionToken?:string, StartSession?:array{LedgerName:string}, StartTransaction?:array{}, EndSession?:array{}, CommitTransaction?:array{TransactionId:string, CommitDigest:string|resource|\Psr\Http\Message\StreamInterface}, AbortTransaction?:array{}, ExecuteStatement?:array{TransactionId:string, Statement:string, Parameters?:array<array{IonBinary?:string|resource|\Psr\Http\Message\StreamInterface, IonText?:string}>}, FetchPage?:array{TransactionId:string, NextPageToken:string}} $args
     * @return \GuzzleHttp\Promise\Promise<array{StartSession?:array{SessionToken?:string, TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, StartTransaction?:array{TransactionId?:string, TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, EndSession?:array{TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, CommitTransaction?:array{TransactionId?:string, CommitDigest?:string|resource|\Psr\Http\Message\StreamInterface, TimingInformation?:array{ProcessingTimeMilliseconds?:int}, ConsumedIOs?:array{ReadIOs?:int, WriteIOs?:int}}, AbortTransaction?:array{TimingInformation?:array{ProcessingTimeMilliseconds?:int}}, ExecuteStatement?:array{FirstPage?:array{Values?:array<array{IonBinary?:string|resource|\Psr\Http\Message\StreamInterface, IonText?:string}>, NextPageToken?:string}, TimingInformation?:array{ProcessingTimeMilliseconds?:int}, ConsumedIOs?:array{ReadIOs?:int, WriteIOs?:int}}, FetchPage?:array{Page?:array{Values?:array<array{IonBinary?:string|resource|\Psr\Http\Message\StreamInterface, IonText?:string}>, NextPageToken?:string}, TimingInformation?:array{ProcessingTimeMilliseconds?:int}, ConsumedIOs?:array{ReadIOs?:int, WriteIOs?:int}}}>
     */
    public function sendCommandAsync(array $args = []): \GuzzleHttp\Promise\Promise { }
}
